### ISSUE TITLE
Logtool seting script

### ISSUE THREAD

**Issue by DarkoMutavdzic** [Rayckey/ActuatorController_ROS#2]
Hey, I used your code to run my INNFOS actuator (QDD Lite-NE30-36), and when I started the ROS node with "rosrun actuatorcontroller_ros innfos_actuator", he told me I needed to run "Logtool setting script to enable log" and I don't know what is that? Can you please help me?

**Comment by xu-yang16** [comment]
As far as I know, it doesn't matter. Therefore, I believe it is OK to just ignore it.

**Comment by DarkoMutavdzic** [comment]
No, you need logtool, you can not skip that. I found them in this repository: https://github.com/mintasca/innfos-cpp-sdk
